apiVersion: v1
kind: Pod
metadata:
  name: kubestore-pod
  labels:
    app: kubestore
spec:
  containers:
    - name: kubestore-container
      image: kubestore:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 8080