apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestore-deployment
  labels:
    app: kubestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubestore
  template:
    metadata:
      labels:
        app: kubestore
    spec:
      containers:
      - name: kubestore-container
        image: kubestore:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          - name: APP_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: kubestore-config
                key: APP_MESSAGE
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kubestore-secret
                key: DB_PASSWORD