apiVersion: v1
kind: Service
metadata:
  name: kubestore-service
spec:
  type: NodePort
  selector:
    app: kubestore  # O Service busca Pods com esta label (deve ser a mesma do Deployment)
  ports:
    - protocol: TCP
      port: 80         # Porta que o Service expõe internamente no Cluster
      targetPort: 8080 # Porta onde a sua aplicação (Flask) está ouvindo
      nodePort: 30007  # Porta que você usará no navegador (deve estar entre 30000-32767)